name: Build

on:
  push:
    branches:
      - 'main'

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: frontend/resumerift
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/rishit-singh/resumerift:latest
            
  # deployment: 
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy docker package on LCSC server (its the most convenient way we have to quickly deploy docker containers)
  #       uses: fjogeleit/http-request-action@v1
  #       with:
  #         url: 'https://watchtower.langaracs.tech/v1/update'
  #         method: 'GET'
  #         bearerToken: ${{ secrets.WATCHTOWER_HTTP_API_TOKEN }}
